src/Entity/FrontMessage.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FrontMessageRepository")
 */
class FrontMessage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=1023)
     */
    private $body;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }
}

src/Entity/LeaseRequest.php
<?php

declare(strict_types=1);

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Repository\PriceRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LeaseRequestRepository")
 * @ORM\Table(name="lease_request")
 *
 * Defines the properties of the Post entity to represent the blog posts.
 *
 * See https://symfony.com/doc/current/book/doctrine.html#creating-an-entity-class
 *
 * Tip: if you have an existing database, you can generate these entity class automatically.
 * See https://symfony.com/doc/current/cookbook/doctrine/reverse_engineering.html
 *
 * @author Wouter van Harten <wouter@woutervanharten.nl>
 */
class LeaseRequest {
    /**
     * Use constants to define configuration options that rarely change instead
     * of specifying them under parameters section in config/services.yaml file.
     *
     * See https://symfony.com/doc/current/best_practices/configuration.html#constants-vs-configuration-options
     */
    public const NUM_ITEMS = 15;
    public const ASSOCIATION_TYPES = array(
        "Scouting Regio" => 'ass_type.regio',
        "Scouting buiten regio" => 'ass_type.scouting',
        "Dispuut" => 'ass_type.dispuut',
        "Studievereniging" => 'ass_type.sv',
        "Overig" => 'ass_type.other', );

    public const STATUSES = array(
        "status.placed",        //  0
        "status.contract",      //  1
        "status.signed",        //  2
        "status.leased",        //  3
        "status.deposit_retour",//  4
        "status.rejected",      //  5
        "status.retracted",     //  6
        "status.occupied",      //  7
        "status.reopened",      //  8
        "status.finished", );   //  9

    public const KEYTIMES = array(
        'label.noon' => '12:30',
        'label.afternoon' => '17:30',
        'label.evening' => '22:00',
        'label.not_known' => null,
    );

    private const REGIO_PP = 'regio_pp';
    private const SCOUTING_pp = 'scouting_pp';
    private const REGIO_MIN = 'regio_min';
    private const SCOUTING_MIN = 'scouting_min';
    private const OTHER_MIN = 'other_min';
    private const OTHER_MAX = 'other_max';
    private const DEPOSIT_SCOUTING = 'deposit_scouting';
    private const DEPOSIT_OTHER = 'deposit_other';
    private const OTHER_DAY = 'other_day';
    private const SCOUTING_DAY = 'scouting_day';
    private const REGIO_DAY = 'regio_day';

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=false)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="slug", type="string", length=255, nullable=false)
     */
    private $slug;

    /**
     * @var string
     *
     * @ORM\Column(name="summary", type="string", length=255, nullable=false)
     */
    private $summary;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="published_at", type="datetime", nullable=false)
     */
    private $publishedAt;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="start_date", type="datetime", nullable=true)
     */
    private $start_date;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="end_date", type="datetime", nullable=true)
     */
    private $end_date;

    /**
     * @var string
     *
     * @ORM\Column(name="association_type", type="string", nullable=false)
     */
    private $association_type;

    /**
     * @var float|null
     *
     * @ORM\Column(name="price", type="float", nullable=true)
     */
    private $price;

    /**
     * @var int|null
     *
     * @ORM\Column(name="status", type="integer", nullable=true)
     */
    private $status;

    /**
     * @var int
     *
     * @ORM\Column(name="num_attendants", type="integer", nullable=false)
     */
    private $num_attendants;

    /**
     * @var string
     *
     * @ORM\Column(name="association", type="string", nullable=false)
     */
    private $association;

    /**
     * @var string|null
     *
     * @ORM\Column(name="contract", type="string", nullable=true)
     */
    private $contract;

    /**
     * @var string|null
     *
     * @ORM\Column(name="contract_signed", type="string", nullable=true)
     */
    private $contract_signed;

    /**
     * @var bool|null
     *
     * @ORM\Column(name="read", type="boolean", nullable=true)
     */
    private $read;

    /**
     * @var float|null
     *
     * @ORM\Column(name="paid", type="float", nullable=true)
     */
    private $paid;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="key_deliver", type="datetime", nullable=true)
     */
    private $key_deliver;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="key_return", type="datetime", nullable=true)
     */
    private $key_return;

    /**
     * @var int
     *
     * @ORM\Column(name="deposit_retour", type="integer")
     */
    private $deposit_retour;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="post", cascade={"persist","remove"}, orphanRemoval=true)
     * @ORM\OrderBy({
     *     "publishedAt"="DESC"
     * })
     */
    private $comments;

    /**
     * @var \App\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="leases", cascade={"persist","remove"})
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="author_id", referencedColumnName="id")
     * })
     */
    private $author;

    public function __construct() {
        $this->publishedAt = new \DateTime();
        $this->comments = new ArrayCollection();
        $this->setStatus(0);
        $this->status = 0;
        $this->setAssociationType('ass_type.other');
        $this->deposit_retour = false;
    }

    public function setPriceRepository(PriceRepository $repository) {
        $this->priceRepository = $repository;
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getTitle(): ?string {
        return $this->title;
    }

    public function setTitle(string $title): void {
        $this->title = $title;
    }

    public function getSlug(): ?string {
        return $this->slug;
    }

    public function setSlug(string $slug): void {
        $this->slug = $slug;
    }

    public function getPublishedAt(): \DateTime {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTime $publishedAt): void {
        $this->publishedAt = $publishedAt;
    }

    public function getAuthor(): ?User {
        return $this->author;
    }

    public function setAuthor(User $author): void {
        $this->author = $author;
    }

    public function getComments(): Collection {
        return $this->comments;
    }

    public function addComment(Comment $comment): void {
        $comment->setPost($this);
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
        }
        $this->setPublishedAt(new \DateTime());
    }

    public function removeComment(Comment $comment): void {
        $this->comments->removeElement($comment);
    }

    public function getSummary(): ?string {
        return $this->summary;
    }

    public function setSummary(string $summary): void {
        $this->summary = $summary;
    }

    public function getStartDate(): ?\DateTimeInterface {
        return $this->start_date;
    }

    public function setStartDate(?\DateTimeInterface $start_date): self {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): self {
        $this->end_date = $end_date;

        return $this;
    }

    public function getAssociationType(): ?string {
        return $this->association_type;
    }

    public function setAssociationType(string $association_type): self {
        $this->association_type = $association_type;

        return $this;
    }

    public function getPrice(): ?float {
        return $this->price;
    }

    public function setPrice(?float $price): self {
        $this->price = $price;

        return $this;
    }

    public function guessPrice(): float {
        $days = $this->getEndDate()->diff($this->getStartDate())->format("%a");
        $regio_pp = $this->priceRepository->findById(self::REGIO_PP)[0]->getPrice();
        $regio_min = $this->priceRepository->findById(self::REGIO_MIN)[0]->getPrice();
        $regio_day = $this->priceRepository->findById(self::REGIO_DAY)[0]->getPrice();
        $scouting_pp = $this->priceRepository->findById(self::SCOUTING_pp)[0]->getPrice();
        $scouting_min = $this->priceRepository->findById(self::SCOUTING_MIN)[0]->getPrice();
        $scouting_day = $this->priceRepository->findById(self::SCOUTING_DAY)[0]->getPrice();
        $other_min = $this->priceRepository->findById(self::OTHER_MIN)[0]->getPrice();
        $other_max = $this->priceRepository->findById(self::OTHER_MAX)[0]->getPrice();
        $other_day = $this->priceRepository->findById(self::OTHER_DAY)[0]->getPrice();

        switch ($this->getAssociationType()) {
            case 'ass_type.regio':
                if ($days == 0) {
                    return $regio_day;
                } else {
                    return max($regio_pp * $this->getNumAttendants(), $regio_min) * $days;
                }
                break;

templates/pdf/contract.html.twig
<html>
<head><meta http-equiv=Content-Type content="text/html; charset=UTF-8">
<style type="text/css">
<!--
span.cls_002{font-family:"Calibri",serif;font-size:11.1px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_002{font-family:"Calibri",serif;font-size:11.1px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_007{font-family:Arial,serif;font-size:20.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_007{font-family:Arial,serif;font-size:20.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_003{font-family:Arial,serif;font-size:10.0px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_003{font-family:Arial,serif;font-size:10.0px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_008{font-family:Arial,serif;font-size:20.1px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_008{font-family:Arial,serif;font-size:20.1px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_004{font-family:Arial,serif;font-size:12.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_004{font-family:Arial,serif;font-size:12.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_005{font-family:Arial,serif;font-size:12.1px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_005{font-family:Arial,serif;font-size:12.1px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_009{font-family:Arial,serif;font-size:10.0px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: underline}
div.cls_009{font-family:Arial,serif;font-size:10.0px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_006{font-family:Arial,serif;font-size:10.0px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_006{font-family:Arial,serif;font-size:10.0px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_010{font-family:Arial,serif;font-size:12.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: underline}
div.cls_010{font-family:Arial,serif;font-size:12.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
-->
</style>
<script type="text/javascript" src="c64f98a0-40c1-11e9-9d71-0cc47a792c0a_id_c64f98a0-40c1-11e9-9d71-0cc47a792c0a_files/wz_jsgraphics.js"></script>
</head>
<body>
<div style="position:absolute;left:50%;margin-left:-297px;top:0px;width:595px;height:841px;border-style:outset;overflow:hidden">
<div style="position:absolute;left:0px;top:0px">
<img src="{{ app.request.getSchemeAndHttpHost() ~ asset('build/images/background_contract.jpg') }}" width=595 height=841></div>
<div style="position:absolute;left:31.08px;top:121.38px" class="cls_007"><span class="cls_007">HUUROVEREENKOMST LAMBARENE</span></div>
<div style="position:absolute;left:456.58px;top:131.46px" class="cls_003"><span class="cls_003">nr.</span></div>
<div style="position:absolute;left:489.22px;top:121.38px" class="cls_008"><span class="cls_008">R{{leaseRequest.id}}</span></div>
<div style="position:absolute;left:29.88px;top:146.58px" class="cls_004"><span class="cls_004">Verhuurder:</span></div>
<div style="position:absolute;left:131.42px;top:146.58px" class="cls_005"><span class="cls_005">Stichting tot behartiging belangen van Scouting Essnlaand</span></div>
<div style="position:absolute;left:131.42px;top:162.09px" class="cls_005"><span class="cls_005">p.a. Oldenzaalsestraat 990</span></div>
<div style="position:absolute;left:342.33px;top:162.09px" class="cls_005"><span class="cls_005">7524 AJ   Lonneker</span></div>
<div style="position:absolute;left:131.18px;top:176.97px" class="cls_003"><span class="cls_003">(</span><span class="cls_009">Geen</span><span class="cls_006"> </span><span class="cls_003">postadres! Contract inscannen en </span><span class="cls_009">mailen</span><span class="cls_003">!)</span></div>
<div style="position:absolute;left:29.88px;top:206.01px" class="cls_010"><span class="cls_010">Gebouw Lambarene, Horstlindelaan 251, 7522  JG  Enschede</span></div>
<div style="position:absolute;left:29.64px;top:249.45px" class="cls_006"><span class="cls_006">Huurder</span></div>
<div style="position:absolute;left:131.18px;top:249.45px" class="cls_003"><span class="cls_003">Naam</span></div>
<div style="position:absolute;left:281.57px;top:249.45px" class="cls_003"><span class="cls_003">{{leaseRequest.association}} (type:{{leaseRequest.associationType}})</span></div>
<div style="position:absolute;left:131.18px;top:262.53px" class="cls_003"><span class="cls_003">t.n.v</span></div>
<div style="position:absolute;left:281.57px;top:262.53px" class="cls_003"><span class="cls_003">{{ leaseRequest.author.fullname }}</span></div>
<div style="position:absolute;left:131.18px;top:275.01px" class="cls_003"><span class="cls_003">Adres</span></div>
<div style="position:absolute;left:281.57px;top:275.01px" class="cls_003"><span class="cls_003">{{leaseRequest.author.address}}</span></div>
<div style="position:absolute;left:131.18px;top:287.49px" class="cls_003"><span class="cls_003">Telefoon</span></div>
<div style="position:absolute;left:281.57px;top:287.49px" class="cls_003"><span class="cls_003">{{leaseRequest.author.phone}}</span></div>
<div style="position:absolute;left:131.18px;top:299.97px" class="cls_003"><span class="cls_003">E-mailadres</span></div>
<div style="position:absolute;left:281.57px;top:299.97px" class="cls_003"><span class="cls_003">{{leaseRequest.author.email}}</span></div>
<div style="position:absolute;left:29.64px;top:312.45px" class="cls_003"><span class="cls_003">Huurperiode van:</span></div>
<div style="position:absolute;left:138.74px;top:312.45px" class="cls_003"><span class="cls_003">{{leaseRequest.startDate |localizeddate('medium', 'none', null, 'UTC')}}</span></div>
<div style="position:absolute;left:394.39px;top:312.45px" class="cls_003"><span class="cls_003">{{leaseRequest.endDate |localizeddate('medium', 'none', null, 'UTC')}}</span></div>
<div style="position:absolute;left:335.71px;top:318.21px" class="cls_003"><span class="cls_003">t/m</span></div>
<div style="position:absolute;left:29.64px;top:324.93px" class="cls_003"><span class="cls_003">Sleutel moment:</span></div>
<div style="position:absolute;left:138.74px;top:324.93px" class="cls_003"><span class="cls_003">later te bepalen</span></div>
<div style="position:absolute;left:394.39px;top:324.93px" class="cls_003"><span class="cls_003">later te bepalen</span></div>
<div style="position:absolute;left:29.64px;top:349.79px" class="cls_006"><span class="cls_006">HUUR en BORG</span></div>
<div style="position:absolute;left:29.64px;top:362.87px" class="cls_003"><span class="cls_003">HUUR</span></div>
<div style="position:absolute;left:134.54px;top:362.87px" class="cls_003"><span class="cls_003">€</span></div>
<div style="position:absolute;left:158.78px;top:362.87px" class="cls_003"><span class="cls_003">{{leaseRequest.price|number_format(2,',')}}</span></div>
<div style="position:absolute;left:281.57px;top:362.87px" class="cls_003"><span class="cls_003">HUURPRIJS deel 1</span></div>
<div style="position:absolute;left:390.19px;top:362.87px" class="cls_003"><span class="cls_003">€</span></div>
<div style="position:absolute;left:414.43px;top:362.87px" class="cls_003"><span class="cls_003">{{(leaseRequest.price/2)|number_format(2,',')}}</span></div>
<div style="position:absolute;left:29.64px;top:375.35px" class="cls_003"><span class="cls_003">WAARBORG</span></div>
<div style="position:absolute;left:111.45px;top:375.35px" class="cls_003"><span class="cls_003">+</span></div>
<div style="position:absolute;left:134.54px;top:375.35px" class="cls_003"><span class="cls_003">€</span></div>
<div style="position:absolute;left:158.78px;top:375.35px" class="cls_003"><span class="cls_003">{{leaseRequest.deposit|number_format(2,',')}}</span></div>
<div style="position:absolute;left:281.57px;top:375.35px" class="cls_003"><span class="cls_003">HUURPRIJS deel 2</span></div>
<div style="position:absolute;left:390.19px;top:375.35px" class="cls_003"><span class="cls_003">€</span></div>
<div style="position:absolute;left:414.43px;top:375.35px" class="cls_003"><span class="cls_003">{{(leaseRequest.price/2+leaseRequest.deposit)|number_format(2,',')}}</span></div>
<div style="position:absolute;left:29.64px;top:387.71px" class="cls_003"><span class="cls_003">Totaal borg en huur</span></div>
<div style="position:absolute;left:134.54px;top:387.71px" class="cls_006"><span class="cls_006">€</span></div>
<div style="position:absolute;left:158.78px;top:387.71px" class="cls_006"><span class="cls_006">{{(leaseRequest.price+leaseRequest.deposit)|number_format(2,',')}}</span></div>
<div style="position:absolute;left:29.64px;top:408.26px" class="cls_005"><span class="cls_005"><b>Betaling</b></span></div>
<div style="position:absolute;left:29.64px;top:424.53px" class="cls_005"><span class="cls_005">De <b><u>huur</b></u> dient overgemaakt te worden naar:</span></div>
<div style="position:absolute;left:290.64px;top:424.53px" class="cls_005"><span class="cls_005">RABO Bank: NL46 RABO 0127 2354 85 o.v.v.: R{{leaseRequest.id}}</span></div>
<div style="position:absolute;left:29.64px;top:440.53px" class="cls_005"><span class="cls_005">De <b><u>borg</b></u> dient overgemaakt te worden naar:</span></div>
<div style="position:absolute;left:290.64px;top:440.53px" class="cls_005"><span class="cls_005">ING Bank: NL85 INGB 0008 9523 66 o.v.v.: R{{leaseRequest.id}}</span></div>
<div style="position:absolute;left:29.64px;top:489.47px" class="cls_009"><span class="cls_009">Ondertekening</span></div>
<div style="position:absolute;left:29.88px;top:502.46px" class="cls_005"><span class="cls_005">Huurder gaat akkoord met de in de bijlage genoemde huurvoorwaarden.</span></div>
<div style="position:absolute;left:29.64px;top:528.26px" class="cls_003"><span class="cls_003">Handtekening huurder</span></div>
<div style="position:absolute;left:301.61px;top:528.26px" class="cls_003"><span class="cls_003">de Stichting</span></div>
<div style="position:absolute;left:100.58px;top:606.14px" class="cls_003"><span class="cls_003">Naam</span></div>
<div style="position:absolute;left:168.02px;top:606.14px" class="cls_003"><span class="cls_003">{{leaseRequest.author.fullName}}</span></div>
<div style="position:absolute;left:336.19px;top:606.14px" class="cls_003"><span class="cls_003">Naam</span></div>
<div style="position:absolute;left:416.86px;top:606.14px" class="cls_003"><span class="cls_003">{{app.user.fullName}}</span></div>
<div style="position:absolute;left:45.00px;top:630.26px" class="cls_010"><span class="cls_010">één ingevuld en ondertekend exemplaar s.v.p. retour zenden</span></div>
<div style="position:absolute;left:45.00px;top:660.52px" class="cls_004"><span class="cls_004">Huur en borg overmaken op bovenstaand rekeningnummer.</span></div>
<div style="position:absolute;left:45.00px;top:675.64px" class="cls_004"><span class="cls_004">Huur deel 1 te voldoen op het moment ondertekenen contract</span></div>
<div style="position:absolute;left:45.00px;top:690.76px" class="cls_004"><span class="cls_004">Huur deel 2 te voldoen minimaal één maand voor aanvang verhuur</span></div>
</div>

</body>
</html>